### ISSUE TITLE
Different Keyboards

### ISSUE THREAD

**Issue by GreatAssetToTheCompany** [Toemmsen96/ChatCommands#1]
Here's a issue i've found, every or almost every mod uses a QWERTY keyboard, problem is that the mods are unplayable on different keyboard languages, if possible, please write patches for different languages of keyboards, thanks!

**Comment by Toemmsen96** [comment]
Hi, what keyboard languages are you talking about? I am using a Swiss layout myself and that works, however the key to open chat is somewhere different (for me it is the "-_" key). This is dependant on the game itself.

If you are talking about any non latin language, that uses different symbols like kyrillic or chinese or whatever, i will probably not be able to make it.
Otherwise if you give me more details it may be possible.

**Comment by GreatAssetToTheCompany** [comment]
What im saying is that uhm..Since most mods use the / in the ENGLISH keyboard language it is basically impossible to play if you have any other language, such as me, i'm brazilian using a brazilian language and i can't play it.

**Comment by GreatAssetToTheCompany** [comment]
I've tested some things such as change the button to another one but they also did not work.

**Comment by gento873** [comment]
what keyboard do you have

**Comment by GreatAssetToTheCompany** [comment]
What??

**Comment by Toemmsen96** [comment]
So you have you tried changing the prefix in the config? It may not fully work with the nonhost stuff, but it should work for you as the host. I still need to fix the network communication if you change the prefix but that doesnt seem to be your issue.

If you have changed the prefix inside the config, can you send me what you input as the command and what the logs say. You should see the thing you input in the log as a Recieved Chat Input and then what you wrote in the chat.

Also have you checked if there is any error listed in the log?

**Comment by GreatAssetToTheCompany** [comment]
I did exactly that, changed the thing in the prefix, nothing worked, the errors in the log i've not tried tho so i will do it right now also may i know if you have a discord so i can maybe talk to you more about it?

**Comment by GreatAssetToTheCompany** [comment]
Okay here's something, it says Invalid or Null chat input when i press ; to chat

**Comment by GreatAssetToTheCompany** [comment]
I figured ; is / in the english language but i can't seem to get it right on the config.

**Comment by Toemmsen96** [comment]
you can also set the prefix to something like cmd: in the config and it should work without a problem
It doesnt need to be / in the end, you can use any string you would like to start the command, just make sure, that you dont leave a space between your set prefix and the command itself.
also, i updated the mod and it fixes some prefix stuff, you may want to check that out.

**Comment by Toemmsen96** [comment]
does this solve your issue @GreatAssetToTheCompany ?
