### ISSUE TITLE
Command `/term` not working as intended

### ISSUE THREAD

**Issue by ToxesFoxes** [Toemmsen96/ChatCommands#10]
No terminal view on screen after used `/term` command
![image](https://github.com/Toemmsen96/ChatCommands/assets/29871037/9f4279c3-5e3b-4d0e-a6b6-ab9f6f9aa964)

Expected:
Working on screen terminal like GameMaster (but GameMaster's terminal is buggy)

Minimum reproducible mod list 
![image](https://github.com/Toemmsen96/ChatCommands/assets/29871037/81f54f84-4323-4933-909c-e849c90b2bc6)

**Comment by Toemmsen96** [comment]
this is actually working as intended. Gamemaster breaks some vanilla ingame terminal animations and stuff and this terminal is just to type out terminal commands from anywhere. i will probably not implement a terminal screen into this but maybe just a simpler list of usable commands or just where you see what you type. For now it just enters commands into the terminal directly, you can see this if you are inside the ship and are looking at the terminal.

**Comment by Toemmsen96** [comment]
/term is now working differently as it just sends the commands itself, no more weird terminal stuck stuff. just use /term "terminalcommand"
using this with buy makes it instantly buy after submitting
