### ISSUE TITLE
Incompatibility - With "Boombox_Controller v1.1.5" Mod by KoderTeh

### ISSUE THREAD

**Issue by jwidess** [Toemmsen96/ChatCommands#12]
Using both of these mods together causes ChatCommands to not register even when changing the Command Prefix to something else. This is most likely a problem with the "[Boombox_Controller](https://thunderstore.io/c/lethal-company/p/KoderTeh/Boombox_Controller/)" mod, but it KoderTeh doesn't seem to have a GitHub so I thought I'd open the issue here instead.

**Comment by Toemmsen96** [comment]
can you send some screenshots so i can see what is entered and what shows?
This shouldnt happen, it probably is the boombox_controller

**Comment by Toemmsen96** [comment]
it is the boombox_controller mod, because it just clears chat inputs for some reason

**Comment by Toemmsen96** [comment]
https://github.com/Koder-Teh/Boombox-Controller/issues here is their github, i found it in the wiki pages.

**Comment by Toemmsen96** [comment]
he updated it, can you tell me if it works now?

**Comment by jwidess** [comment]
> he updated it, can you tell me if it works now?

Yep works fine even with the same command prefix!

**Comment by Toemmsen96** [comment]
perfect
