### ISSUE TITLE
"Random seed:" Message Stuck on Screen

### ISSUE THREAD

**Issue by jwidess** [Toemmsen96/ChatCommands#13]
When hosting a server with this mod (and many others) installed, the "[Random seed: xxxxxx](https://external-preview.redd.it/our-quickest-game-of-lethal-company-yet-v0-a3dvMXd3Zjc1cmFjMfsi1qO26fN5YzxBoKEgtqXr5_x_rmzThBKMr8TqeanC.png?format=pjpg&auto=webp&s=884b54eb330f9f0f458cd3597828ff54d3355e7e)" message gets stuck on everyone but the host's screen when landing on a planet. I have ~41 other mods installed so it could be an incompatibility, but ChatCommands was throwing a few logs in particular that might be relevant. Also, my config is below as that might have something to do with it however, I didn't test different config settings. Attached is the full log from a client connecting to my server with the ChatCommands mod installed on both. The error I noticed ChatCommands throw is at line **1104**.

**Thunderstore Profile Code:** `018cfbf1-e733-2741-4b00-59501e828474`

## My Config:
```
## Settings file was created by plugin ChatCommands v1.1.6
## Plugin GUID: toemmsen.ChatCommands

[Command Settings]

## An optional prefix for chat commands
# Setting type: String
# Default value: /
Command Prefix = /

## (for server host only): determines if clients can also use the host commands
# Setting type: Boolean
# Default value: true
Has to be Host = false

## (for server host only): determines if commands get sent to the clients, so for example god mode is enabled for them too
# Setting type: Boolean
# Default value: true
Send Host Commands = false
```

**Comment by Toemmsen96** [comment]
Can you send a screenshot of the log where the error happens?

**Comment by jwidess** [comment]
> Can you send a screenshot of the log where the error happens?

Oh sorry I forgot to attach the log file! Its attached below, ChatCommands error happens at line 1104.

## [ChatCommands on Non-Host.log](https://github.com/Toemmsen96/ChatCommands/files/13915278/ChatCommands.on.Non-Host.log)

**Comment by Toemmsen96** [comment]
Thx, i think i found the issue. I added a host check for the needed function and the update should be live soon

**Comment by jwidess** [comment]
@Toemmsen96 awesome! Thanks again for your phenomenal support on this awesome mod! I'll test it out and report back when the new update hits.

**Comment by Toemmsen96** [comment]
> @Toemmsen96 awesome! Thanks again for your phenomenal support on this awesome mod! I'll test it out and report back when the new update hits.

Perfect, thanks for the feedback!!
