### ISSUE TITLE
Arguments don't support spaces (e.g. Usernames with Spaces)

### ISSUE THREAD

**Issue by rsiebertdev** [Toemmsen96/ChatCommands#14]
In Lethal Company LAN games, everybody's username follows the naming scheme "Player #**1**", "Player #**2**", etc which contain spaces.

Commands such as `/cohost <username>` won't work with these usernames, because the argument handler considers any spaces to be the start of a new argument. https://github.com/Toemmsen96/ChatCommands/blob/51be709af35f1b846862b253a848550779f26d6b/ChatCommands/Plugin.cs#L217

I think there should be an exception using quotations, allowing spaces to be entered into arguments themselves. This would allow "Player #**1**" to be interpreted as 1 argument as opposed to 2 by just surrounding it with quotes like so:
```
/cohost "Player #2"
```

**Comment by Toemmsen96** [comment]
oh yeah, i didnt think about lan, will look into that

**Comment by Toemmsen96** [comment]
Will be fixed with the next update, only thing you need to do is leave away the space in the name. For example Player#0
