### ISSUE TITLE
Mod breaking enemies spawn logic of the game

### ISSUE THREAD

**Issue by JO-Step** [Toemmsen96/ChatCommands#15]
Currently this mod seems to break enemies spawn logic, enemies such as ghost girl originally will spawn only one in a time, but with the mod they could spawn multiple amounts. It may be caused by spawning functions in this mod but this is not supposed to happen in ordinary play. Is it able to fix the spawn logic to vanilla as soon as the enemy spawn function is not used? Or adding configs to disable/enable some specific commands?

**Comment by Toemmsen96** [comment]
hmm okay, i will look into that

**Comment by Toemmsen96** [comment]
Will be togglable with the commands /override or /ovr and configurable in the configs in the next update :)

**Comment by Toemmsen96** [comment]
it now is configurable with that ^
