### ISSUE TITLE
Spawning commands broken

### ISSUE THREAD

**Issue by SammichLS** [Toemmsen96/ChatCommands#16]
spawn scrap and spawn enemy commands are not working. For example, I typed this in: /spwscr Airhorn p=@me and it said it spawned, but there was nothing there. I tried multiple times inside and outside but nothing worked. Enemy spawning had the same issue. All commands were used on the moon experimentation and I only tried enemies and scrap listed as available.

Edit: After seeing that @me is broken, I used @playername to select myself and it did not recognize me as a player.

**Comment by SammichLS** [comment]
My fault for not seeing that @me is broken currently, I tested without putting any location and would like to know if it defaults to random of it it's broken as well.

**Comment by RedPiss** [comment]
Having the same issues here,  I believe they don't work after the first day.

**Comment by RedPiss** [comment]
Also, when doing /enemies, it comes up with nothing.

**Comment by Toemmsen96** [comment]
@me should work again, im not sure if the game had an update that broke the mod in the meantime. Im in the middle of uni exams atm, i will look into it after them.

**Comment by Toemmsen96** [comment]
Also, can you provide logs, otherwise i cannot see what the issue might be, if it doesnt appear for me.

**Comment by Toemmsen96** [comment]
> Also, when doing /enemies, it comes up with nothing.
> 

If you use it as non host that is a know issue. As host it should work

**Comment by SammichLS** [comment]
Log for one spawn attempt:
<img width="1280" alt="Screenshot 2024-01-22 114633" src="https://github.com/Toemmsen96/ChatCommands/assets/157324422/8078f2b2-c251-4928-a457-51c400c70449">

[Info   :toemmsen.ChatCommands] Received chat input: /spwscr Airhorn a=1 p=@me v=5
[Info   :toemmsen.ChatCommands] Player who called: Sammich_LS
[Info   :toemmsen.ChatCommands] Amount 1
[Info   :toemmsen.ChatCommands] @me
[Info   :toemmsen.ChatCommands] Checking Playername SammichLS
[Info   :toemmsen.ChatCommands] Checking Playername Player #1
[Info   :toemmsen.ChatCommands] Checking Playername Player #2
[Info   :toemmsen.ChatCommands] Checking Playername Player #3
[Info   :toemmsen.ChatCommands] Value 5
[Info   :toemmsen.ChatCommands] Spawning 1 Airhorn

If needed I have video clips of me trying spawn enemy and scrap commands but can't upload them here.
I tested them on a used save using a mod profile only containing your mod and its dependency.

**Comment by Toemmsen96** [comment]
hmm okay, it looks like there is an issue with it detecting your name. Does your name contain a "_" character or a space?

**Comment by SammichLS** [comment]
My steam name is Sammich_LS and my in game name appears to be SammichLS. I tried both and got the same result

**Comment by Toemmsen96** [comment]
I believe there is an issue with how the game saves your name. Have you tried p=@SammichLS? The way i check who called the command is via the games input, so im kind of confused why this appears like that.

**Comment by Toemmsen96** [comment]
![image](https://github.com/Toemmsen96/ChatCommands/assets/147745097/4ccb0dbf-f571-4622-a67f-dc70a39daefe)
Found the issue, i will adjust my code according to it. This should enable lan players as well

**Comment by Toemmsen96** [comment]
i pushed an update, i believe it should be fixed now, otherwise please just write here again
