### ISSUE TITLE
god mode is bugged

### ISSUE THREAD

**Issue by GemmyGustavo** [Toemmsen96/ChatCommands#17]
there is a issue on god mode where whenver you die from outside enemies (Who hit kills such as eyeless dog and forest giant) you simply you can't interact with anything,
such as:
starting ship, closing doors, grabbing loot, etc

please fix

**Comment by Toemmsen96** [comment]
Yeah, its been an issue for a while, i might look into it next week, if it is a quick fix i will do it, otherwise probably not, sorry

**Comment by GemmyGustavo** [comment]
okay thanks its just that i test some things and then suddendly a eyeless dog comes out "kills" me with god mode and then i have to wait for the rest of the round

**Comment by Toemmsen96** [comment]
Sorry it took so long but i fixed it in version 1.1.92
