### ISSUE TITLE
@me and @playername issue.

### ISSUE THREAD

**Issue by LethalCompanyEnjoyer** [Toemmsen96/ChatCommands#19]
I'm having the same issue but the @me and @playername **BOTH** don't work, so I'm at a loss. They both just put the items in the facility,
![image_2024-06-02_010642142](https://github.com/Toemmsen96/ChatCommands/assets/171468444/60e16279-d45d-4fe0-bffc-e8d6a79d49c4)
![image](https://github.com/Toemmsen96/ChatCommands/assets/171468444/b21ef7d2-47bb-42cf-8093-5b00c0fbfec1)

**Comment by Toemmsen96** [comment]
Use it without the ( )- Brackets. These are just there to emphasize that they are optional in the description
So like /spwscr PillBottle a=5 p=@me v=10000

**Comment by Toemmsen96** [comment]
The default value of a is 1 so if you just want one you can leave that away and the default of v is 1000

**Comment by Toemmsen96** [comment]
> I'm having the same issue but the @me and @playername **BOTH** don't work, so I'm at a loss. They both just put the items in the facility, ![image_2024-06-02_010642142](https://private-user-images.githubusercontent.com/171468444/335841316-60e16279-d45d-4fe0-bffc-e8d6a79d49c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTk3ODksIm5iZiI6MTcxNzMxOTQ4OSwicGF0aCI6Ii8xNzE0Njg0NDQvMzM1ODQxMzE2LTYwZTE2Mjc5LWQ0NWQtNGZlMC1iZmZjLWU4ZDZhNzlkNDljNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwOTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzYzZGZhMzAwNzRmYzVhZmQwMDVmYmQzNGJlYjIzZTM3MTkxOGU3NDEzMGU1MDJlMDhlYWFjM2Q0OTNiYWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1TwqAPIVXLuw_39g0wOzy7M41_zPcjCUl5Ou50UpGKY) ![image](https://private-user-images.githubusercontent.com/171468444/335841338-b21ef7d2-47bb-42cf-8093-5b00c0fbfec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTk3ODksIm5iZiI6MTcxNzMxOTQ4OSwicGF0aCI6Ii8xNzE0Njg0NDQvMzM1ODQxMzM4LWIyMWVmN2QyLTQ3YmItNDJjZi04MDkzLTViMDBjMGZiZmVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwOTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGE3NDgwNzMwMDZkZGI3YzE3ZjdhOGIyZDMzZGU1ZGQ1YjY5M2U0ZGU0NTg5MGE0OGYyYTc4YmNiNzQxMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L_8Czfjz85ZEuHoPaECy3dbn05WVx69xC6P39rmEra4)

And for p=@"playername" you would replace "playername" with your name or the players one you want to spawn it on, for example: /spwscr cog p=LethalCompanyEnjoyer

**Comment by LethalCompanyEnjoyer** [comment]
Thanks for fixing the problem! 👍
