### ISSUE TITLE
spawn command not working properly

### ISSUE THREAD

**Issue by gento873** [Toemmsen96/ChatCommands#2]
when i use
/spweny [enemyname] a=1 p=@me
it summons a completely different enemy
exemple: /spweny Spring a=1 p=@me and it summons a hoarding bug
and when i use /spwscr [scrapname] a=1 p=@me it just dosent summon
any help ?

and also: when i spawn gun with /spwscr,i just cant use anything anymore,cant pick up stuff,cant open terminal, cant even start the ship

**Comment by Toemmsen96** [comment]
You may need to chech with /enemies and /getscrap to see if the things you are trying to spawn are available on the map. Then try using that name for the thing you are trying to spawn

The gun thing i also realised, i will look into that

**Comment by Toemmsen96** [comment]
Also if you are trying to spawn only one scrap item you dont need to specify the amount, doesnt really solve the issue tho

**Comment by gento873** [comment]
iam checking the /getscrap and the /enemies but it just dosent change anything

**Comment by gento873** [comment]
for enemies even if i do one that is spawnable it will take mutliple tries to get,and for scrap it will never spawn, ionly managed to get it to spawn 1 time in singleplayer

**Comment by gento873** [comment]
I'll retry with /enemies and /getscrap but it prob wont work

**Comment by Toemmsen96** [comment]
Hmmm, that is weird, can you provide logs?

**Comment by gento873** [comment]
lemme just grab them,i'll have to do sum else for scrap logs tho
alsoforgot to mention that outside enemies work
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/c54c943e-becd-48db-b889-b6646b6697db)
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/d9aa91e7-5311-4929-85b2-dbdba216750a)
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/dca3f734-564c-4cfc-8802-a45bc085546f)

**Comment by gento873** [comment]
oops put 2 of the same

**Comment by Toemmsen96** [comment]
it seems like the enemies get spawned, however you may not encounter them right at the moment. try spawning the spring with p=@me to see if it spawns on you (before that maybe enable godmode so you dont die right away).
I might need to change the function how enemies spawn randomly so it doesnt require a vent for them to spawn.
aditionally: if you only spawn one enemy randomly you don't need to clarify p=random and a=1, for example like this: /spweny spring

**Comment by gento873** [comment]
i do spawn with p=@me most of the time,lemme go in a solo match and fetch that really quick

**Comment by gento873** [comment]
i got lucky <with the spring being good on the first try but then this spawned a centipede
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/06b3591c-6ac5-4cf4-88fc-e766b0ce2299)

**Comment by gento873** [comment]
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/21422034-1f23-477b-a18b-6a11beb855ff)
and yet, distant err unknown or sum like that appears

**Comment by Toemmsen96** [comment]
yess, i figured that it still displays an error even if there isnt any, i need to change that because some of it is a false error (forgot to change that in the newest version)

**Comment by Toemmsen96** [comment]
> i got lucky <with the spring being good on the first try but then this spawned a centipede ![image](https://private-user-images.githubusercontent.com/146378056/293671041-06b3591c-6ac5-4cf4-88fc-e766b0ce2299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTEyMTUsIm5iZiI6MTcwNDE5MDkxNSwicGF0aCI6Ii8xNDYzNzgwNTYvMjkzNjcxMDQxLTA2YjM1OTFjLTZhYzUtNGNmNC04OGZjLWU3NjZiMGNlMjI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMDIxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmNlYzdjOWFhYTg2MWI4OTZmZGYzOWYzNDUwY2FiNmIzNWNjODdlOWZkNmE3NjA2MjNhZDIzMWZiMzgwMzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gv3bMO5y7V0QkWWRA8uWwp6Df5b_YYsSOlKiHTtFtho)

i think i know what the issue is, i will look into that. i think i fetched a list of spawnable enemies, that dont actually correspond with the right index. you might be able to spawn the nutcracker anyway if you try a different name

**Comment by gento873** [comment]
ye,one time i tried to spawna  spring,it spawned an hoarding bug so i spawned the hoarding bug to get the spring,its just annoying because one time the i spawned a monster,didnt w<ork,tried to spawn what it spawned and it spawned the wrong again,but thanks for looking into it

**Comment by gento873** [comment]
whta about the scrap tho ? are you like gonna contact the one that made the scrap thing ?

**Comment by Toemmsen96** [comment]
> whta about the scrap tho ? are you like gonna contact the one that made the scrap thing ?

i will improve on that, im testing some things atm

> ye,one time i tried to spawna spring,it spawned an hoarding bug so i spawned the hoarding bug to get the spring,its just annoying because one time the i spawned a monster,didnt w<ork,tried to spawn what it spawned and it spawned the wrong again,but thanks for looking into it

try using it on a different map, i when we made the thing we used the experimentation map to test stuff and it worked there, but the enemy indexes are sometimes different on other maps

**Comment by gento873** [comment]
ah,i already tried multiple times on  experimentation but still dosent work

**Comment by Toemmsen96** [comment]
yeah, i will look into it, i guess it may not have been experimentation, but yeah.
however i found why some of the spawn scrap code doesnt work as it should, because i had some of the code in the wrong place after improving the code structure 😅 my fault

**Comment by gento873** [comment]
ight thank you !!

**Comment by Toemmsen96** [comment]
i believe i fixed the scrap thing, the gun is still broken, and the enemy part i still need to look into

**Comment by gento873** [comment]
that's nice !

**Comment by gento873** [comment]
i assume you're gonna release the update when you have fixed everything

**Comment by Toemmsen96** [comment]
yess, maybe without the gun, i think that will take more to fix

**Comment by gento873** [comment]
alright

**Comment by Toemmsen96** [comment]
found the issue with the enemies not being the right one, i had a typo in there, i will upload the update soon

**Comment by Toemmsen96** [comment]
update is live now

**Comment by gento873** [comment]
thank you ! ima test it in solo

**Comment by Toemmsen96** [comment]
perfect, thanks for the feedback!   
If you are using the mod manager it may take up to half an hour until you get the update tho.
Dragging the files in manually should work

**Comment by gento873** [comment]
ight,if there is any more errors i'll tell you !

**Comment by Toemmsen96** [comment]
👍🏼 thanks.
just fyi, the gun isn't fixed yet, it will take some more time to find out how to spawn it properly without errors and stuff, but there is a new feature where you can set the value of scrap using v="value" when spawning the scrap items, so you may test that as well if you want.

**Comment by gento873** [comment]
ok so the enemies work bt the scrap dosent work and it just changed the error to
distant
ERR unknown@[myusername]

**Comment by gento873** [comment]
i used
/spwscr Hairbrush a=1 p=@me or /spwscr Hairbrush p=@me

**Comment by gento873** [comment]
i'll retry with value

**Comment by gento873** [comment]
nope still dosent work

**Comment by gento873** [comment]
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/008fdaa0-f624-4a79-b17b-601d20e74771)

**Comment by gento873** [comment]
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/242abcb6-1f71-49ba-a56e-29b82c6bcc8d)

**Comment by Toemmsen96** [comment]
can you try it with cog really quick?

**Comment by Toemmsen96** [comment]
as the scrap part

**Comment by gento873** [comment]
ight gimme a sec

**Comment by Toemmsen96** [comment]
i do also get the same error sometimes, cog always works for me for whatever reason, so i guess i did my testing a little wrong 😅

**Comment by gento873** [comment]
cog still dosent work lmao

**Comment by Toemmsen96** [comment]
can you try just typing them in lowercase, i think that is the issue lol

**Comment by gento873** [comment]
![image](https://github.com/Toemmsen96/ChatCommands/assets/146378056/55389ae7-847d-45b5-8db1-4c2e14bf5cd9)
this was the attempt with the uppercase

**Comment by gento873** [comment]
if it is the issue,maybe put the scraps in lowercase lmao

**Comment by Toemmsen96** [comment]
yes, i added the lowercase thing for everything except for the scrap name because i guess i just forgot, i will add the ToLowercase() and update it. i will probably also add an error message so you get asked if you used /getscrap to see if the thing you are trying to spawn is even spawnable on this map

**Comment by gento873** [comment]
yep you're right,the uppercase causes the error

**Comment by gento873** [comment]
i managed to spawn a hairbrush with a value of 1543 so yep that's nice

**Comment by Toemmsen96** [comment]
perfect, i will update it right away

**Comment by gento873** [comment]
alright nice

**Comment by Toemmsen96** [comment]
updated it
