### ISSUE TITLE
I don't know how what to do

### ISSUE THREAD

**Issue by ocrgwareva** [Toemmsen96/ChatCommands#21]
I keep trying to spawn enemies so i type out /spweny lootbug a=10 p=random  why does that not work i dont understand

**Comment by Toemmsen96** [comment]
Are there any errors that pop up in the console or the log file?

And have you checked if p=@me works? It could be that you just dont see the lootbugs if you spawn them random because they are far away. 

And have you tried other commands and if they work?

**Comment by ocrgwareva** [comment]
I've tried the get scrap which works perfectly fine it's literally just that one I tried thumper as well and nutcracker and none of them work and there's no errors

**Comment by Toemmsen96** [comment]
> I've tried the get scrap which works perfectly fine it's literally just that one I tried thumper as well and nutcracker and none of them work and there's no errors 

Is override spawns turned on? And maybe try checking with /enemies to see if you can spawn those on the current planet.

Also, have you tried the mod without any other mods installed? Could be a conflict.

Otherwise i will have to check if i have the same issue.

**Comment by ocrgwareva** [comment]
Idk what override spawns is and how do I do /enemies is it just the same. I'll try by itself

**Comment by Toemmsen96** [comment]
> Idk what override spawns is and how do I do /enemies is it just the same. I'll try by itself

Should all be described in this Repositorys ReadMe. /enemies just lists all enemies that usually spawn on the current map. /override should toggle if you can spawn more monsters than usual on the map.

`/override or /ovr -> toggle overriding enemy spawns. If set to true there can be more than one girl spawned automatically etc.
If set to false, enemies spawned using /spawnenemy might not spawn. Default can be set in cfg.`

**Comment by ocrgwareva** [comment]
It works now dw
