### ISSUE TITLE
/togglehostcmd and /thcmd straight up do not work.

### ISSUE THREAD

**Issue by Mudkipster** [Toemmsen96/ChatCommands#23]
They just display an error in the yellow box when used. Honestly there isn't much else to say.

**Comment by Toemmsen96** [comment]
Thanks for the feedback. I will try to rework the mod entirely soon and try to fix this.

**Comment by Toemmsen96** [comment]
> They just display an error in the yellow box when used. Honestly there isn't much else to say.

Should actually still work, just the message was default in this version you are using, so it showed the yellow box, because i forgot to add a message.
