### ISSUE TITLE
/god prevent you from being killed by monsters in some instances

### ISSUE THREAD

**Issue by emitlinks** [Toemmsen96/ChatCommands#24]
This bug happens when you enable godmode with /god, get attacked by a monster (which can't kill you because of godmode) and then disabling godmode.

The console shows in loop when monster is attacking you : **[Info   : Unity Log] Player is not targetable**

You can still be killed by fall damage, or I guess environmental stuff like explosion (I only tried falling to my death while the bug is active).

Just so I'm sure this isn't a compatibility issue with another mod, I tried in a modpack with only chatcommands.

You can reproduce this easily : 
1. Enable godmode with /god command
2. Spawn a mouthdog with /spawnenemy command
3. Get attacked by mouthdog
4. DIsable godmode with /god command
5. Try to get killed by mouthdog

**Comment by Toemmsen96** [comment]
New update is up where a lot has changed, Let me know if this still is the same for you

**Comment by emitlinks** [comment]
The update seems to have fixed this bug.
