### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by NotAvailablePleaseTryAgainLater** [Toemmsen96/ChatCommands#25]
So i tried downloading this (duh) and whenever i tried to use commands in a public server it would just make my messages show up as as a single space, and not do anything. and whenever i tried to do it alone in a server i hosted it said this, help?

![20241119182658_1](https://github.com/user-attachments/assets/9f080c2c-bb8d-43f4-89a0-f50a3687c839)

**Comment by Toemmsen96** [comment]
You cant use the Host commands in public servers if the host doesnt have the mod. Also: what command did you use and did try you start going to a moon?
CuttentLevel is zero when you are in orbit.

In the future it will not be needed to visit a moon to be able to spawn stuff anymore, but rn it is.

**Comment by NotAvailablePleaseTryAgainLater** [comment]
> You cant use the Host commands in public servers if the host doesnt have the mod. Also: what command did you use and did try you start going to a moon? CuttentLevel is zero when you are in orbit.
> 
> In the future it will not be needed to visit a moon to be able to spawn stuff anymore, but rn it is.

thanks man!
