### ISSUE TITLE
problems when giving a list

### ISSUE THREAD

**Issue by TOMEEATER** [Toemmsen96/ChatCommands#4]
whenever it tries to give a list of things it just puts a blank space in the chat
<img width="201" alt="Screenshot 2024-01-02 204915" src="https://github.com/Toemmsen96/ChatCommands/assets/155504561/75d2a2e8-3777-4475-96b3-8b86870f9d39">
this is after I entered "/spawn"

**Comment by Toemmsen96** [comment]
Are you in a multiplayer game?

**Comment by gento873** [comment]
oh no,dont worry that happens often,jjust type in stuff in chat until chat works again

**Comment by Toemmsen96** [comment]
as far as i know this issue only appears when there are more than one person in the lobby, but im not sure why it happens. i believe it is a bug in the games code itself tbh

**Comment by Toemmsen96** [comment]
i believe this should be fixed now with the newest update (1.1.5)
