### ISSUE TITLE
Spawn Enemy won't spawn at my player

### ISSUE THREAD

**Issue by ietesla** [Toemmsen96/ChatCommands#5]
When trying to spawn an enemy from the list, it doesn't spawn them at my player with "@me"

Example command:  /spawnenemy Dog a=1 p=@me
it doesn't spawn it at my position

Is this wrong syntax? I don't know.

**Comment by Toemmsen96** [comment]
No, it should be right, can you provide a screenshot what the console says when you enter that?

**Comment by Toemmsen96** [comment]
You can also use /spweny mouthdog p=@me to spawn only one on you

**Comment by gento873** [comment]
you need to type in mouthdog not dog

**Comment by Toemmsen96** [comment]
> When trying to spawn an enemy from the list, it doesn't spawn them at my player with "@me"
> 
> Example command: /spawnenemy Dog a=1 p=@me it doesn't spawn it at my position
> 
> Is this wrong syntax? I don't know.

it may help to use /enemies to get what the spawnable enemies are on the map and how they are called

**Comment by Toemmsen96** [comment]
i have found an issue where it gets the wrong reference player, i will try to fix that, but in mean time just use it with @ and your playername, for example for me it would be @Toemmsen96
